import type { Metadata } from "next";
import { roboto, bitcountGridDouble } from './fonts';
import "./globals.css";

export const metadata: Metadata = {
  title: "Desert Animals Classifier",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.className} ${bitcountGridDouble.className} antialiased`} >
      <body>
        {children}
      </body>
    </html>
  );
}
