import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Bitcount_Grid_Double from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bitcountGrid = Bitcount_Grid_Double({
  src: [
    { path: "./fonts/BitcountGridDouble_Cursive-Black", weight: "400", style: "normal" },
    { path: "./fonts/Poppins-Italic.woff2",  weight: "400", style: "italic" },
    { path: "./fonts/Poppins-Bold.woff2",    weight: "700", style: "normal" },
    { path: "./fonts/Poppins-BoldItalic.woff2", weight: "700", style: "italic" },
  ],
  variable: "--font-bitcount_grid_double",          // <— CSS var Tailwind can use
  display: "swap",
});

export const metadata: Metadata = {
  title: "Desert Animals Classifier",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bitcountGrid.variable">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
